### ISSUE TITLE
Trigger a new build to update the base image

### ISSUE THREAD

**Issue by thedrow** [pypy/manylinux#8]
pypa/manylinux2010_x86_64 has last changed two weeks ago.

The last release of this image was two months ago.
We need to trigger a new build and push a new image.

**Comment by antocuni** [comment]
I triggered a new build: https://travis-ci.org/github/pypy/manylinux/builds/704260408

**Comment by antocuni** [comment]
@thedrow the build succeeded, so the latest pypy-manylinux docker image should contain the required changes. Do you confirm?

**Comment by thedrow** [comment]
Works. Thank you.
